### ISSUE TITLE
Additional information in common.model.EndPoint class

### ISSUE THREAD

**Issue by PeterOlausson65** [difi/vefa-peppol#16]
In the common.model.EndPoint.class, there are some elements in the ServiceMetaData that are not available in the EndPoint class. 
- TechnicalContactUrl
- TechnicalInformationUrl
- ServiceActivationDate
- ServiceExpirationDate
- ServiceDescription

Would it be possible to have these in the EndPoint model, and also populated from the lookup.reader.Bdxreader class?

**Comment by klakegg** [comment]
3 of 5 is not included in the next release of SMP specification, thus is not to be included. The remining 2 is now included.
