### ISSUE TITLE
Rem Evidence missing Attribute version

### ISSUE THREAD

**Issue by Chanderbhan** [difi/vefa-peppol#2]
If the REM Evidence is based on ETSI TS 102 640-2 V2.2.1 (2011-09) then it is 
missing  element “Attribute version” because this element is in that case mandatory.
The value is  "1" for this version.

**Comment by steinarcook** [comment]
Ouch, that was a mistake on my part. Fixed by adding a test and hard coding the "version" attribute to the value of "1".

I wonder if our xsd is compliant with ETSI revision 2.2.1 - need to check that.
