### ISSUE TITLE
9921 IT:IPA Deprecated, new ICD to be added

### ISSUE THREAD

**Issue by sabandosoleda** [difi/vefa-peppol#28]
Hi everybody,

Today many italian PA identifiers were migrated to a new ICD, 0201, effectively breaking compatibility with oxalis, which now raises an IllegalStateException when validating documents using this new ICD.

See here for the news about the migration: https://intercenter.regione.emilia-romagna.it/notizie/2019/novembre/aggiornati-i-participant-id-peppol

Here's the deprecated code:
https://github.com/difi/vefa-peppol/blob/be3fc670d5a27ab9516a6458a612ffb3fbac5164/peppol-icd/src/main/java/no/difi/vefa/peppol/icd/code/PeppolIcd.java#L74

A new line such as 
`IT_NEW_IPA("IT:IPA", "0201", "Indice delle Pubbliche Amministrazioni"),`
Should be added to support the compatibility with participants using the new ID without breaking the ones that haven't switched yet.

**Comment by klakegg** [comment]
ICD `0201` is not part of the official OpenPEPPOL "Participant Identifier Schemes" code list, currently version "v5".

**Comment by sabandosoleda** [comment]
Yes, but you can verify that `9921 - IT:IPA` is Deprecated in favour of `0201` in version "v6" (https://github.com/OpenPEPPOL/documentation/tree/master/Code%20Lists#v6---work-in-progress). 
Despite v6 being work in progress, the main italian IPA access points have already started using the new ICD.

**Comment by sabandosoleda** [comment]
Reconsidering what I said about adding a new line in the enum though, I'm pretty sure that couldn't work because we'd have a collision on the IT:IPA constant inside documents. 
What would you recommend to do if one had to support both codes at the moment?

**Comment by klakegg** [comment]
Difi is currently performing migration of ICDs. If Agid wants to discuss migration plans with Difi, please contact us through normal channels.

**Comment by sabandosoleda** [comment]
That's good news. 
By the way, I have no relation to Agid, nor I am an institutional representative of any kind. I just opened this issue to report the technical issue that Agid/IntercentER's "abrupt" migration caused and as a reference for other oxalis users that might be facing it.
