### ISSUE TITLE
Determine UBL versionID in ehf:forward-billing:3.0

### ISSUE THREAD

**Issue by HarshaSuranjith** [difi/vefa-peppol#29]
In EHF 3.0 ubl version was removed and inferred UblVersionId 2.1 was used to generate the document type Identifier.

But with the `ehf:forward-billing:3.0` UBL version is specified as 2.2 and document does not contain the version as well. This creates a conflic in identifying the proper UBL version. 

How to determine the proper UBL version from the document ??

**Comment by klakegg** [comment]
How is this related to the content of this repository?

**Comment by HarshaSuranjith** [comment]
Ok, where else can I get this information  ?

**Comment by klakegg** [comment]
The relevance to this repo is not clear.
