### ISSUE TITLE
Verify all eSENS requirements are adhered to 

### ISSUE THREAD

**Issue by steinarcook** [difi/vefa-peppol#5]
Verify that all eSENS requirements are adhered to in accordance with what was discussed in Brussels on March 14th.

**Comment by sfieten** [comment]
One issue is that the current implementation inserts the instance identifier from the SDBH (`//DocumentIdentification/InstanceIdentifier`) in `//SenderMessageDetails/UAMessageIdentifier` where the v1.4 specs require the instance identifier to be inserted in `//SenderMessageDetails/MessageIdentifierByREMMD`

**Comment by sfieten** [comment]
Also missing is the `EvidenceIssuerDetails` element. According to the e-SENS profile it should contain the entity name of the gateway, so should be set by creator of REM evidence.

**Comment by sfieten** [comment]
Another missing element is `EvidenceIssuerPolicyID` and its `PolicyID` child elements which should contain the identifier of the policy used for creating the evidence. 
Although the e-SENS profile states that this element is optional (as does the xsd from the REM evidence spec) it is a required element according to section 5.1.4 of the REM evidence spec.

**Comment by sfieten** [comment]
Last element currently missing in the evidence implementation is `EvidenceRefersToRecipient`. This element is used to identify to which recipient the evidence refers in case the message has multiple. But as message in e-SENS have only one recipient this element is not relevant. However the element is set to required in section 5.1.4 of the REM spec and therefore should be included. But this may be an error in the spec as its description in 5.2.2.3.4 says it is only needed when multiple recipients are listed.

**Comment by sfieten** [comment]
Last difference noted between specs and current implementation is that the signature is currently a "plain" XML signature instead of a "full fledged" Xades one.

**Comment by sfieten** [comment]
The requirement stated in the ETSI specification that the `EvidenceRefersToRecipient` field is always required is incorrect. It is only mandatory when multiple recipients are included in the evidence. As this is not possible in e-SENS profile, there is no need to add this field.

**Comment by steinarcook** [comment]
Thanks a lot for your contributions, Sander.

I am closing this issue as it seems we have covered the lot.
